aggiunta appunti e notebook elly
unipr-org/QC pull request #9
Opened 2024-10-10 09:58 UTC by manueldiagostino

2024-10-10 10:41 UTC, merendamattia requested changes

2024-10-10 10:41 UTC, merendamattia commented on qiskit/jupyter-notebook/README.md
> +docker compose up --build --no-start
Non funziona su macos con lo spazio al posto del trattino. Se non funziona su linux con il trattino bisogna fare due versioni per i comandi

2024-10-10 10:41 UTC, merendamattia commented on qiskit/jupyter-notebook/README.md
> +docker compose up -d
uguale in tutti gli altri casi

2024-10-11 08:27 UTC, merendamattia approved these changes

2024-10-11 08:37 UTC, SimoneColli approved these changes

2024-10-11 08:37 UTC, merged